## Практическое задание 1

Все задания рекомендуется делать вручную, проверяя полученные результаты через NumPy.

__1.__ Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    
__2.__ Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.

__5*.__ Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

## Решение
***Задача 1 (вручную и с проверкой на NumPy)***

In [13]:
print("Общее правило определения произведения AB матриц A и B: размеры матрицы B должны быть согласованы с размерами матрицы A,\nили число строк матрицы B должно быть равно числу столбцов матрицы A.")
print("При размерности матрицы A m*n и матрицы B n*p размерность произведения AB равна m*p\n")
print("a) AB не определено; BA не определено")
print("б) AB определено, размерность 2 x 3; BA не определено")
print("в) AB определено, размерность 8 x 8; BA определено, размерность 3 x 3")
print("г) AB определено, размерность 4 x 4; BA определено, размерность 4 x 4")

Общее правило определения произведения AB матриц A и B: размеры матрицы B должны быть согласованы с размерами матрицы A,
или число строк матрицы B должно быть равно числу столбцов матрицы A.
При размерности матрицы A m*n и матрицы B n*p размерность произведения AB равна m*p

a) AB не определено; BA не определено
б) AB определено, размерность 2 x 3; BA не определено
в) AB определено, размерность 8 x 8; BA определено, размерность 3 x 3
г) AB определено, размерность 4 x 4; BA определено, размерность 4 x 4


In [14]:
import numpy as np

In [15]:
dimensions = []
dimensions.append([[4,2],[4,2]])
dimensions.append([[2,5],[5,3]])
dimensions.append([[8,3],[3,8]])
dimensions.append([[4,4],[4,4]])
print(f"Размеры матриц А и В: {dimensions}\n")

for el in dimensions:
    A = np.ones((el[0][0], el[0][1]))
    B = np.ones((el[1][0], el[1][1]))
    s = "A " + str(A.shape) + ", B " + str(B.shape) + ":    A*B "
    try:
        C = np.dot(A,B)
        s1 = str(C.shape)
    except:
        s1 = " ---- "
    s = s + s1 + "   B*A "
    try:
        C = np.dot(B,A)
        s1 = str(C.shape)
    except:
        s1 = " ---- "
    s += s1
    print(s)
    


Размеры матриц А и В: [[[4, 2], [4, 2]], [[2, 5], [5, 3]], [[8, 3], [3, 8]], [[4, 4], [4, 4]]]

A (4, 2), B (4, 2):    A*B  ----    B*A  ---- 
A (2, 5), B (5, 3):    A*B (2, 3)   B*A  ---- 
A (8, 3), B (3, 8):    A*B (8, 8)   B*A (3, 3)
A (4, 4), B (4, 4):    A*B (4, 4)   B*A (4, 4)


***Задача 2***

In [16]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f"A:\n{A}\n\nB:\n{B}\n\nA + B:\n{A+B}\n\nA * B:\n{np.dot(A,B)}")

A:
[[ 1 -2]
 [ 3  0]]

B:
[[ 4 -1]
 [ 0  5]]

A + B:
[[ 5 -3]
 [ 3  5]]

A * B:
[[  4 -11]
 [ 12  -3]]


***Задача 3***

In [17]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f"Матрица A:\n{A}\n\nМатрица B:\n{B}\n\nМатрица C:\n{C}\n")
print(f"Матрица 3*A:\n{3*A}\n\nМатрица 2*B:\n{2*B}\n\nМатрица 4*C:\n{4*C}\n")
print(f"Линейная комбинация 3*A - 2*B + 4*C:\n{3*A - 2*B + 4*C}\n")


Матрица A:
[[ 1  7]
 [ 3 -6]]

Матрица B:
[[ 0  5]
 [ 2 -1]]

Матрица C:
[[ 2 -4]
 [ 1  1]]

Матрица 3*A:
[[  3  21]
 [  9 -18]]

Матрица 2*B:
[[ 0 10]
 [ 4 -2]]

Матрица 4*C:
[[  8 -16]
 [  4   4]]

Линейная комбинация 3*A - 2*B + 4*C:
[[ 11  -5]
 [  9 -12]]



***Задача 4***

In [18]:
A = np.array([[4,1],[5,-2],[2,3]])
B = A.T
print(f"Матрица А:\n{A}\n\nМатрица А транспонированная:\n{B}\n")
print(f"Произведение A*A.T:\n{np.dot(A,B)}\n\nПроизведение A.T*A:\n{np.dot(B,A)}")

Матрица А:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]

Матрица А транспонированная:
[[ 4  5  2]
 [ 1 -2  3]]

Произведение A*A.T:
[[17 18 11]
 [18 29  4]
 [11  4 13]]

Произведение A.T*A:
[[45  0]
 [ 0 14]]


***Задача 5: функция перемножения 2-х произвольных матриц без использования NumPy***

In [19]:
def MultMatrix(A,B):
    A_rows = len(A)
    B_rows = len(B)
    A_cols = -1
    B_cols = -1
    for i, el in enumerate(A):
        if i == 0:
            A_cols = len(el)
        elif A_cols != len(el):
            return None
    for i, el in enumerate(B):
        if i == 0:
            B_cols = len(el)
        elif B_cols != len(el):
            return None
    
    if A_rows < 1 or A_cols < 1 or B_rows < 1 or B_cols < 1 or A_cols != B_rows:
        return None
    
    C = []

    for i in range(A_rows):
        D = []
        for j in range(B_cols):
            s = 0
            for k in range(A_cols):
                s += A[i][k] * B[k][j]
            D.append(s)
        C.append(D)
    return C

#------- Формируются матрицы, как в задаче 4: исходная (А) и траспонированная (В)

A = []
A.append([4,1])
A.append([5,-2])
A.append([2,3])

B = []
B.append([4,5,2])
B.append([1,-2,3])

lst = [['A', 'B'], ['B', 'A']]

print(f"{lst[0][0]}: {A}, {lst[0][1]}: {B}")

#------- Вычисляем с помощью нашей функции A*B и B*A

for i in range(2):
    if i == 0:
        C = MultMatrix(A,B)
    else:
        C = MultMatrix(B,A)
    if C != None:
        print(f"{lst[i][0]} * {lst[i][1]}:\n{C}")
    else:
        print("Размеры матриц несогласованы или некорректны")

A: [[4, 1], [5, -2], [2, 3]], B: [[4, 5, 2], [1, -2, 3]]
A * B:
[[17, 18, 11], [18, 29, 4], [11, 4, 13]]
B * A:
[[45, 0], [0, 14]]


## Практическое задание 2

Все задания рекомендуется выполнять вручную, проверяя полученные результаты с использованием NumPy.

__1.__ Вычислите определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


__2.__ Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__3.__  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__4.__ Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

***Задача 1***

In [20]:
A = np.array([[np.sin(30), -np.cos(30)], [np.cos(30), np.sin(30)]])
print(f"а) det A = {round(np.linalg.det(A), 0):.0f}")
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f"б) det A = {round(np.linalg.det(A), 0):.0f}")
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"в) det A = {round(np.linalg.det(A), 0):.0f}")

а) det A = 1
б) det A = 180
в) det A = 0


***Задача 2***

In [21]:
A = np.array([[3, 5], [4, 8]])
print(f"Матрица А:\n{A}\n")
print(f"det A = {round(np.linalg.det(A), 0):.0f}\n")
print(f"a) det A*A = {round(np.linalg.det(np.dot(A,A)), 0):.0f}")
print(f"б) det A.T = {round(np.linalg.det(A.T), 0):.0f}")
print(f"в) det A*2 = {round(np.linalg.det(A*2), 0):.0f}")

Матрица А:
[[3 5]
 [4 8]]

det A = 4

a) det A*A = 16
б) det A.T = 4
в) det A*2 = 16


***Задача 3***

In [22]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f"Матрица А:\n{A}\n")
try:
    det_a = round(np.linalg.det(A), 0)
    print(f"det A = {det_a:.0f}")
    if (det_a == 0):
        print("Матрица вырожденная")
    else:
        print("Матрица невырожденная")
except:
    print("Матрица неквадратная")

Матрица А:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]

det A = 0
Матрица вырожденная


***Задача 4***

In [24]:
for i in range(2):
    if i == 0:
        A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
    else:
        A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
    print(f"Матрица А:\n{A}\n")
    print(f"Ранг матрицы А равен {np.linalg.matrix_rank(A)}\n")


Матрица А:
[[1 2 3]
 [1 1 1]
 [2 3 4]]

Ранг матрицы А равен 2

Матрица А:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]

Ранг матрицы А равен 3

