## Практическое задание

__1.__ Найдите собственные векторы и собственные значения для линейного оператора, заданного матрицей:

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

In [47]:
import numpy as np

a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
print(f'Матрица A:\n{a}\n')
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]

Собственные значения:
[2. 3.]

Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


In [48]:
def check_for_eig(matr, vect):
    m = np.dot(matr, vect)
    print(f'Линейный оператор A:\n{matr}\n')
    print(f'Вектор X:\n{vect}\n')
    print(f'Произведение A*X:\n{m}\n')
    for i in range(len(vect)):
        if i == 0:
            l = m[i] / vect[i]
        elif l != m[i] / vect[i]:
            print(f'Вектор X={vect} не является собственным вектором линейного оператора A, т.к. {m[i]}/{vect[i]} != {l:.0f}\n')
            return
    print(f'Вектор X={vect} является собственным вектором линейного оператора A, т.к. (A*X)/X={l:.0f}\n')

__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей:

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Покажите, что __любой__ вектор считается для него собственным.

In [49]:
print('Нетрудно заметить, что результатом умножения оператора поворота на вектор (m, n) будет вектор (-m, -n), т.е. lambda = -1.')
print('Покажем это на всех возможных сочетаниях знаков m и n, где m и n не равны 0\n')

a = np.array([[-1, 0], [0, -1]])
x = []
x.append([3, -13])
x.append([23, -31])
x.append([23, 31])
x.append([-23, -31])

for i in range(len(x)):
    print(f'{i+1}.')
    check_for_eig(a, x[i])

Нетрудно заметить, что результатом умножения оператора поворота на вектор (m, n) будет вектор (-m, -n), т.е. lambda = -1.
Покажем это на всех возможных сочетаниях знаков m и n, где m и n не равны 0

1.
Линейный оператор A:
[[-1  0]
 [ 0 -1]]

Вектор X:
[3, -13]

Произведение A*X:
[-3 13]

Вектор X=[3, -13] является собственным вектором линейного оператора A, т.к. (A*X)/X=-1

2.
Линейный оператор A:
[[-1  0]
 [ 0 -1]]

Вектор X:
[23, -31]

Произведение A*X:
[-23  31]

Вектор X=[23, -31] является собственным вектором линейного оператора A, т.к. (A*X)/X=-1

3.
Линейный оператор A:
[[-1  0]
 [ 0 -1]]

Вектор X:
[23, 31]

Произведение A*X:
[-23 -31]

Вектор X=[23, 31] является собственным вектором линейного оператора A, т.к. (A*X)/X=-1

4.
Линейный оператор A:
[[-1  0]
 [ 0 -1]]

Вектор X:
[-23, -31]

Произведение A*X:
[23 31]

Вектор X=[-23, -31] является собственным вектором линейного оператора A, т.к. (A*X)/X=-1



__3.__ Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установите, считается ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.


In [50]:
check_for_eig(np.array([[1, 1], [-1, 3]]), np.array([1, 1]))

Линейный оператор A:
[[ 1  1]
 [-1  3]]

Вектор X:
[1 1]

Произведение A*X:
[2 2]

Вектор X=[1 1] является собственным вектором линейного оператора A, т.к. (A*X)/X=2



**4.** Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установите, считается ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

In [51]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
x = np.array([3, -3, -4])
     
check_for_eig(a, x)

Линейный оператор A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]

Вектор X:
[ 3 -3 -4]

Произведение A*X:
[ -9   9 -12]

Вектор X=[ 3 -3 -4] не является собственным вектором линейного оператора A, т.к. -12/-4 != -3

