## Практическое задание 1

__1.__ Решите систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

__2.__ Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$


__3.__ Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

__4.__ Дана система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найдите соотношение между параметрами $a$, $b$ и $c$, при которых система считается несовместной.

In [24]:
import numpy as np

a = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])
print('Задача 3.')
print('---------')
print(f'Определитель матрицы коэффициентов det(A) = {np.linalg.det(a): .0f}')
print(f'Ранг матрицы коэффициентов rank(A) = {np.linalg.matrix_rank(a): .0f}')
print(f'Ранг расширенной матрицы rank(A_) = {np.linalg.matrix_rank(b): .0f}')
print('Cистема совместна по теореме Кронекера-Капелли и имеет единственное решение (ненулевой определитель) при независимых векторах\nстолбцов коэффициентов')

Задача 3.
---------
Определитель матрицы коэффициентов det(A) =  30
Ранг матрицы коэффициентов rank(A) =  4
Ранг расширенной матрицы rank(A_) =  4
Cистема совместна по теореме Кронекера-Капелли и имеет единственное решение (ненулевой определитель) при независимых векторах
столбцов коэффициентов


## Практическое задание 2

__1.__ Решите систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

__2*.__ Найдите $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
    
__3*.__ Решите систему линейных уравнений методом $LU$-разложения:

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

__4*.__ Решите систему линейных уравнений методом Холецкого:

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

__5*.__ Напишите на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [25]:
print('Задания 1 и 5 (с написанием программы для метода Крамера)')
print('---------------------------------------------------------\n')

a1 = np.array([[1, -2], [3, -4]])
b1 = np.array([1, 7])
a2 = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b2 = np.array([10, -2, 1])

def Cramer_decision(a, b):
    res = []
    print(f'Матрица коэффициентов:\n{a}\n')
    print(f'Столбец свободных членов:\n{b}\n')
    det_a = np.linalg.det(a)
    for j in range(len(a[0])):
        c = a.copy()
        for i in range(len(b)):
            c[i][j] = b[i]
        #print(f'{i}: матрица С:\n{c}\n')
        res.append(int(round(np.linalg.det(c)/det_a, 0)))
    print(f'Ответ по методу Крамера: {res}\n')
    return res

arr = []
tmp = []
tmp.append(a1)
tmp.append(b1)
arr.append(tmp.copy())
tmp.clear()
tmp.append(a2)
tmp.append(b2)
arr.append(tmp.copy())
x = []

for i in range(2):
    x = Cramer_decision(arr[i][0], arr[i][1])

Задания 1 и 5 (с написанием программы для метода Крамера)
---------------------------------------------------------

Матрица коэффициентов:
[[ 1 -2]
 [ 3 -4]]

Столбец свободных членов:
[1 7]

Ответ по методу Крамера: [5, 2]

Матрица коэффициентов:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]

Столбец свободных членов:
[10 -2  1]

Ответ по методу Крамера: [2, -1, 1]



In [26]:
from scipy.linalg import lu

def LU_decision(a, b):
    res = [el for el in b]
    i_max = len(a)
    j_max = len(a[0])
    l, u = get_lu_matrix(a)
    
    for i in range (i_max):
        s = b[i]
        for j in range (i + 1):
            if i == j:
                res[j] = s / l[i][j]
            else:
                s -= (l[i][j] * res[j])

    for i in range (i_max - 1, -1, -1):
        s = res[i]
        for j in range (j_max - 1, i - 1, -1):
            if i == j:
                res[j] = s / u[i][j]
            else:
                s -= (u[i][j] * res[j])
    return res

def get_lu_matrix(a):
    i_max = len(a)
    j_max = len(a[0])
    l_m = np.zeros(shape=(i_max, j_max))
    u_m = np.zeros(shape=(i_max, j_max))
    for i in range(i_max):
        for j in range(j_max):
            u_m[i][j] = a[i][j]
    
    for j in range(j_max):
        for i in range(j, i_max):
            if j == i:
                l_m[i][j] = 1
            elif i > j:
                coeff = u_m[i][j] / u_m[j][j]
                l_m[i][j] = coeff
                for k in range(j, j_max):
                    u_m[i][k] -= (coeff * u_m[j][k])
    return l_m, u_m


print('Задания 2 и 5 (с написанием программы для LU-разложения)')
print('--------------------------------------------------------\n')
s = ['a) ', 'б) ']
for i in range(2):
    if i == 0:
        A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
    else:
        A = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
        
    L, U = get_lu_matrix(A)
        
    print(f'{s[i]}Матрица коэффициентов:\n{A}\n')
    print(f'L-матрица:\n{L}\n')
    print(f'U-матрица:\n{U}\n')
    print(f'Проверка - произведение L*U для собственной программы:\n{np.dot(L,U)}\n')

    sp_pl, sp_u = lu(A, permute_l=True)
    print(f'Вариант: PL-матрица для LU-разложения посредством "scipy.linalg.lu":\n{sp_pl}\n')
    print(f'U-матрица для LU-разложения посредством "scipy.linalg.lu":\n{sp_u}\n')
    print(f'Проверка - произведение PL*U для "scipy.linalg.lu":\n{np.dot(sp_pl,sp_u)}\n')

Задания 2 и 5 (с написанием программы для LU-разложения)
--------------------------------------------------------

a) Матрица коэффициентов:
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]

L-матрица:
[[1. 0. 0.]
 [2. 1. 0.]
 [3. 4. 1.]]

U-матрица:
[[1. 2. 4.]
 [0. 5. 4.]
 [0. 0. 2.]]

Проверка - произведение L*U для собственной программы:
[[ 1.  2.  4.]
 [ 2.  9. 12.]
 [ 3. 26. 30.]]

Вариант: PL-матрица для LU-разложения посредством "scipy.linalg.lu":
[[0.33333333 0.8        1.        ]
 [0.66666667 1.         0.        ]
 [1.         0.         0.        ]]

U-матрица для LU-разложения посредством "scipy.linalg.lu":
[[ 3.         26.         30.        ]
 [ 0.         -8.33333333 -8.        ]
 [ 0.          0.          0.4       ]]

Проверка - произведение PL*U для "scipy.linalg.lu":
[[ 1.  2.  4.]
 [ 2.  9. 12.]
 [ 3. 26. 30.]]

б) Матрица коэффициентов:
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]

L-матрица:
[[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [3. 5. 1. 0.]
 [4. 6. 7. 1.]]

U-ма

In [27]:
print('Задания 3 и 5 (с написанием программы для решения СЛАУ методом LU-разложения)')
print('-----------------------------------------------------------------------------\n')

A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
B = np.array([1, -6, -5])
print(f'Матрица коэффициентов:\n{A}\n')
print(f'Вектор свободных членов: {B}\n')
X = LU_decision(A, B)
print(f'Вектор решений: {X}')
print(f'Проверка A*X=B: {np.dot(A, X)}')

Задания 3 и 5 (с написанием программы для решения СЛАУ методом LU-разложения)
-----------------------------------------------------------------------------

Матрица коэффициентов:
[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]

Вектор свободных членов: [ 1 -6 -5]

Вектор решений: [-1.0, 0.0, 1.0]
Проверка A*X=B: [ 1. -6. -5.]


In [28]:
def Cholesky_decision(a, b):
    res = [el for el in b]
    i_max = len(a)
    j_max = len(a[0])
    l = np.linalg.cholesky(a)
    u = l.T
    
    for i in range (i_max):
        s = b[i]
        for j in range (i + 1):
            if i == j:
                res[j] = s / l[i][j]
            else:
                s -= (l[i][j] * res[j])

    for i in range (i_max - 1, -1, -1):
        s = res[i]
        for j in range (j_max - 1, i - 1, -1):
            if i == j:
                res[j] = s / u[i][j]
            else:
                s -= (u[i][j] * res[j])
    return res


print('Задания 4 и 5 (решение СЛАУ встроенным разложением Холецкого с собственным нахождением вектора решений)')
print('-------------------------------------------------------------------------------------------------------\n')

A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
B = np.array([531, -460, 193])
print(f'Матрица коэффициентов:\n{A}\n')
print(f'Вектор свободных членов: {B}\n')
L = np.linalg.cholesky(A)
print(f'L-матрица Холецкого:\n{L}\n')
print(f'Проверка L*L.T=A:\n{np.dot(L, L.T)}\n')
X = Cholesky_decision(A, B)
print(f'Вектор решений: {X}')
print(f'Проверка A*X=B: {np.dot(A, X)}')

Задания 4 и 5 (решение СЛАУ встроенным разложением Холецкого с собственным нахождением вектора решений)
-------------------------------------------------------------------------------------------------------

Матрица коэффициентов:
[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]

Вектор свободных членов: [ 531 -460  193]

L-матрица Холецкого:
[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]

Проверка L*L.T=A:
[[ 81. -45.  45.]
 [-45.  50. -15.]
 [ 45. -15.  38.]]

Вектор решений: [6.0, -5.0, -4.0]
Проверка A*X=B: [ 531. -460.  193.]
