## Практическое задание 1

1. Найдите посредством NumPy SVD для матрицы:

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [40]:
import numpy as np

A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
print(f'Матрица А:\n{A}\n')

Матрица А:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]



In [41]:
np.set_printoptions(precision=2, suppress=True)

U, s, W = np.linalg.svd(A)

print(f'Матрица U:\n{U}\n')
print(f'Проверка ортогональности: матрица U.T*U:\n{np.dot(U.T, U)}\n')
print(f'Матрица W:\n{W}\n')
print(f'Проверка ортогональности: матрица W.T*W:\n{np.dot(W.T, W)}\n')

print(f'Вектор s:\n{s}\n')
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
print(f'Матрица D:\n{D}\n')

print(f'Проверка SVD для матрицы А:\n{np.dot(np.dot(U, D), W)}\n')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]

Проверка ортогональности: матрица U.T*U:
[[ 1. -0.  0.  0.  0.]
 [-0.  1. -0. -0. -0.]
 [ 0. -0.  1.  0. -0.]
 [ 0. -0.  0.  1. -0.]
 [ 0. -0. -0. -0.  1.]]

Матрица W:
[[ 0.07  0.72  0.69]
 [-0.37  0.67 -0.65]
 [-0.93 -0.21  0.31]]

Проверка ортогональности: матрица W.T*W:
[[ 1.  0. -0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]

Вектор s:
[8.82 6.14 2.53]

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]

Проверка SVD для матрицы А:
[[ 1.  2. -0.]
 [-0.  0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [ 0.  1.  0.]]



2. Для матрицы из предыдущего задания найдите:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [45]:
print('\nа) Евклидова норма')
print('------------------\n')
print(f'{np.linalg.norm(A, ord=2):.12f} - linalg.norm с параметром 2')
print(f'{max(s):.12f} - наибольшее сингулярное число')


а) Евклидова норма
------------------

8.824868854820 - linalg.norm с параметром 2
8.824868854820 - наибольшее сингулярное число


In [46]:
print('\nб) норма Фробениуса')
print('-------------------\n')
print(f'{np.linalg.norm(A):.12f} - linalg.norm без параметров')
print(f'{np.linalg.norm(A, ord="fro"):.12f} - linalg.norm с параметром "fro"')

fr = 0
for i in range(len(A)):
    for j in range(len(A[0])):
        fr += A[i][j]**2
fr = np.sqrt(fr)
print(f'{fr:.12f} - расчёт из всех элементов')

fr = 0
for i in range(len(s)):
    fr += s[i]**2
fr = np.sqrt(fr)
print(f'{fr:.12f} - расчёт из сингулярных чисел')


б) норма Фробениуса
-------------------

11.045361017187 - linalg.norm без параметров
11.045361017187 - linalg.norm с параметром "fro"
11.045361017187 - расчёт из всех элементов
11.045361017187 - расчёт из сингулярных чисел
